//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiagramContainer : DbContext
    {
        public DiagramContainer() //: base(@"metadata=res://*/Models.Diagram.csdl|res://*/Models.Diagram.ssdl|res://*/Models.Diagram.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=DESKTOP-8ORRJSS\\NAME;initial catalog=Library;integrated security=True;pooling=False;MultipleActiveResultSets=True;App=EntityFramework&quot;")
            : base("name=DiagramContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<BookExtras> BookExtras { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Readers> Readers { get; set; }
        public virtual DbSet<ArticulBooks> ArticulBooks { get; set; }
    }
}
